object frmChartPages: TfrmChartPages
  Left = 0
  Top = 0
  Width = 1048
  Height = 163
  Align = alClient
  TabOrder = 0
  object Pages: TRzPageControl
    Left = 0
    Top = 0
    Width = 1048
    Height = 163
    Hint = ''
    ActivePage = tsProfile
    Align = alClient
    TabOverlap = -2
    TabIndex = 3
    TabOrder = 0
    FixedDimension = 21
    object tsThickness: TRzTabSheet
      Color = 15987699
      Caption = 'Thickness'
      object chThickness: TChart
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 1038
        Height = 132
        Cursor = crCross
        LeftWall.Visible = False
        Legend.Font.DefaultFont = True
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        MarginBottom = 1
        MarginLeft = 1
        MarginRight = 1
        MarginTop = 2
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        BottomAxis.Axis.Width = 1
        DepthAxis.Axis.Width = 1
        DepthTopAxis.Axis.Width = 1
        LeftAxis.Axis.Width = 1
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Axis.Width = 1
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Axis.Width = 1
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.FontZoom = 200
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztNo
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        BevelWidth = 2
        Color = 15925239
        TabOrder = 0
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
      end
    end
    object tsRoughness: TRzTabSheet
      Color = 15987699
      Caption = 'Roughness'
      object chRoughness: TChart
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 1038
        Height = 132
        Cursor = crCross
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        MarginRight = 0
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        BottomAxis.Axis.Width = 1
        DepthAxis.Axis.Width = 1
        DepthTopAxis.Axis.Width = 1
        LeftAxis.Axis.Width = 1
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Axis.Width = 1
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Axis.Width = 1
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16773087
        TabOrder = 0
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
      end
    end
    object tsDensity: TRzTabSheet
      Color = 15987699
      Caption = 'Density'
      object chDensity: TChart
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 1038
        Height = 132
        Cursor = crCross
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        MarginRight = 0
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        BottomAxis.Axis.Width = 1
        DepthAxis.Axis.Width = 1
        DepthTopAxis.Axis.Width = 1
        LeftAxis.Axis.Width = 1
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Axis.Width = 1
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Axis.Width = 1
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16773087
        TabOrder = 0
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
      end
    end
    object tsProfile: TRzTabSheet
      Color = 15987699
      Caption = 'Profile'
      object chProfile: TChart
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 1038
        Height = 132
        Cursor = crCross
        Border.Width = 0
        BottomWall.Pen.Width = 0
        BottomWall.Pen.Visible = False
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        Legend.Visible = False
        MarginRight = 0
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        BottomAxis.Axis.Width = 1
        DepthAxis.Axis.Width = 1
        DepthTopAxis.Axis.Width = 0
        LeftAxis.Axis.Width = 1
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Axis.Width = 1
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Axis.Width = 1
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16773087
        TabOrder = 0
        DesignSize = (
          1038
          132)
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
        object btnProfileCopy: TRzButton
          Left = 972
          Top = 0
          Width = 59
          Anchors = [akTop, akRight]
          Caption = 'Copy'
          TabOrder = 0
          OnClick = btnProfileCopyClick
        end
        object DensityProfile: TLineSeries
          SeriesColor = 16744448
          Title = 'DensityProfile'
          Brush.BackColor = clDefault
          LinePen.Color = 12615680
          LinePen.Width = 2
          Pointer.InflateMargins = True
          Pointer.Style = psRectangle
          XValues.Name = 'X'
          XValues.Order = loAscending
          YValues.Name = 'Y'
          YValues.Order = loNone
        end
      end
    end
    object tsFittingProgress: TRzTabSheet
      Color = 15987699
      Caption = 'Convergence'
      object chFittingProgress: TChart
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 1038
        Height = 132
        Cursor = crCross
        Border.Color = clDefault
        Border.Visible = True
        Legend.TopPos = 0
        Legend.Visible = False
        MarginBottom = 2
        MarginLeft = 2
        MarginRight = 5
        MarginTop = 5
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        Title.VertMargin = 3
        BottomAxis.Automatic = False
        BottomAxis.AutomaticMaximum = False
        BottomAxis.AutomaticMinimum = False
        BottomAxis.Axis.Width = 1
        BottomAxis.Increment = 10.000000000000000000
        BottomAxis.Maximum = 100.000000000000000000
        BottomAxis.Minimum = -1.000000000000000000
        BottomAxis.Title.Caption = 'Iteration'
        DepthAxis.Axis.Width = 1
        DepthTopAxis.Axis.Width = 1
        LeftAxis.Axis.Width = 1
        LeftAxis.AxisValuesFormat = '#.0 "x10" E+0'
        LeftAxis.ExactDateTime = False
        LeftAxis.Increment = 1.000000000000000000
        LeftAxis.LabelsExponent = True
        LeftAxis.LabelsFormat.Margins.Left = 0
        LeftAxis.LabelsFormat.Margins.Right = 0
        LeftAxis.LabelsFormat.Margins.Bottom = 0
        LeftAxis.LabelsFormat.Margins.Units = maPercentSize
        LeftAxis.LabelsSeparation = 20
        LeftAxis.Logarithmic = True
        LeftAxis.MaximumOffset = 2
        LeftAxis.MaximumRound = True
        LeftAxis.MinimumOffset = 4
        LeftAxis.Title.Caption = #967'2'
        LeftAxis.Title.Font.Height = -13
        LeftAxis.Title.Shadow.Visible = False
        RightAxis.Axis.Width = 1
        TopAxis.Axis.Width = 1
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16771538
        TabOrder = 0
        DesignSize = (
          1038
          132)
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
        object btnCopyConvergence: TRzButton
          Left = 968
          Top = 9
          Width = 59
          Anchors = [akTop, akRight]
          Caption = 'Copy'
          TabOrder = 0
          OnClick = btnCopyConvergenceClick
        end
        object lsrConvergence: TLineSeries
          SeriesColor = 16744448
          Title = 'srFitProgress'
          Brush.BackColor = clDefault
          LinePen.Color = clRed
          LinePen.Width = 2
          Pointer.InflateMargins = True
          Pointer.Style = psRectangle
          Stairs = True
          XValues.Name = 'X'
          XValues.Order = loAscending
          YValues.Name = 'Y'
          YValues.Order = loNone
        end
      end
    end
    object tsDiagnostics: TRzTabSheet
      Color = 15987699
      Caption = 'Diagnostics'
      object chDiagnostics: TChart
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 1038
        Height = 132
        Cursor = crCross
        Border.Color = clDefault
        Border.Visible = True
        Legend.TopPos = 30
        Legend.Visible = True
        Legend.CheckBoxes = True
        MarginBottom = 2
        MarginLeft = 2
        MarginRight = 5
        MarginTop = 5
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        BottomAxis.Automatic = False
        BottomAxis.AutomaticMaximum = False
        BottomAxis.AutomaticMinimum = False
        BottomAxis.Axis.Width = 1
        BottomAxis.Increment = 10.000000000000000000
        BottomAxis.Maximum = 100.000000000000000000
        BottomAxis.Minimum = -1.000000000000000000
        BottomAxis.Title.Caption = 'Iteration'
        DepthAxis.Axis.Width = 1
        DepthTopAxis.Axis.Width = 1
        LeftAxis.Automatic = False
        LeftAxis.AutomaticMaximum = False
        LeftAxis.AutomaticMinimum = False
        LeftAxis.Axis.Width = 1
        LeftAxis.Maximum = 1.100000000000000000
        LeftAxis.Minimum = 0.000000000000000000
        LeftAxis.MaximumOffset = 2
        LeftAxis.MinimumOffset = 4
        RightAxis.Axis.Width = 1
        TopAxis.Axis.Width = 1
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16771538
        TabOrder = 0
        DesignSize = (
          1038
          132)
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
        object btnCopyDiagnostics: TRzButton
          Left = 968
          Top = 9
          Width = 59
          Anchors = [akTop, akRight]
          Caption = 'Copy'
          TabOrder = 0
          OnClick = btnCopyDiagnosticsClick
        end
      end
    end
  end
end
