object frmChartPages: TfrmChartPages
  Left = 0
  Top = 0
  Width = 2096
  Height = 326
  Align = alClient
  TabOrder = 0
  object Pages: TRzPageControl
    Left = 0
    Top = 0
    Width = 2096
    Height = 326
    Hint = ''
    ActivePage = tsThickness
    Align = alClient
    TabOverlap = -2
    TabIndex = 0
    TabOrder = 0
    FixedDimension = 42
    object tsThickness: TRzTabSheet
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Color = 15987699
      Caption = 'Thickness'
      object chThickness: TChart
        AlignWithMargins = True
        Left = 6
        Top = 6
        Width = 2080
        Height = 268
        Cursor = crCross
        Margins.Left = 6
        Margins.Top = 6
        Margins.Right = 6
        Margins.Bottom = 6
        Legend.Font.DefaultFont = True
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        MarginBottom = 1
        MarginLeft = 1
        MarginRight = 1
        MarginTop = 2
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.FontZoom = 200
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztNo
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 15925239
        TabOrder = 0
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
      end
    end
    object tsRoughness: TRzTabSheet
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Color = 15987699
      Caption = 'Roughness'
      object chRoughness: TChart
        AlignWithMargins = True
        Left = 6
        Top = 6
        Width = 2080
        Height = 268
        Cursor = crCross
        Margins.Left = 6
        Margins.Top = 6
        Margins.Right = 6
        Margins.Bottom = 6
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        MarginRight = 0
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16773087
        TabOrder = 0
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
      end
    end
    object tsDensity: TRzTabSheet
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Color = 15987699
      Caption = 'Density'
      object chDensity: TChart
        AlignWithMargins = True
        Left = 6
        Top = 6
        Width = 2080
        Height = 268
        Cursor = crCross
        Margins.Left = 6
        Margins.Top = 6
        Margins.Right = 6
        Margins.Bottom = 6
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        MarginRight = 0
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16773087
        TabOrder = 0
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
      end
    end
    object tsProfile: TRzTabSheet
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Color = 15987699
      Caption = 'Profile'
      object chProfile: TChart
        AlignWithMargins = True
        Left = 6
        Top = 6
        Width = 2080
        Height = 268
        Cursor = crCross
        Margins.Left = 6
        Margins.Top = 6
        Margins.Right = 6
        Margins.Bottom = 6
        Legend.HorizMargin = 5
        Legend.TopPos = 0
        Legend.Visible = False
        MarginRight = 0
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        LeftAxis.MaximumOffset = 4
        LeftAxis.MinimumOffset = 4
        RightAxis.Labels = False
        RightAxis.LabelsFormat.Visible = False
        TopAxis.Labels = False
        TopAxis.LabelsFormat.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16773087
        TabOrder = 0
        DesignSize = (
          2080
          268)
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
        object btnProfileCopy: TRzButton
          Left = 1948
          Top = 0
          Width = 118
          Height = 50
          Margins.Left = 6
          Margins.Top = 6
          Margins.Right = 6
          Margins.Bottom = 6
          Anchors = [akTop, akRight]
          Caption = 'Copy'
          TabOrder = 0
          OnClick = btnProfileCopyClick
        end
        object DensityProfile: TLineSeries
          Title = 'DensityProfile'
          Brush.BackColor = clDefault
          LinePen.Width = 3
          Pointer.InflateMargins = True
          Pointer.Style = psRectangle
          XValues.Name = 'X'
          XValues.Order = loAscending
          YValues.Name = 'Y'
          YValues.Order = loNone
        end
      end
    end
    object tsFittingProgress: TRzTabSheet
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Color = 15987699
      Caption = 'Convergence'
      object chFittingProgress: TChart
        AlignWithMargins = True
        Left = 6
        Top = 6
        Width = 2080
        Height = 268
        Cursor = crCross
        Margins.Left = 6
        Margins.Top = 6
        Margins.Right = 6
        Margins.Bottom = 6
        Border.Color = clDefault
        Border.Visible = True
        Legend.TopPos = 0
        Legend.Visible = False
        MarginBottom = 2
        MarginLeft = 2
        MarginRight = 5
        MarginTop = 5
        MarginUnits = muPixels
        Title.Text.Strings = (
          'TChart')
        Title.Visible = False
        Title.VertMargin = 3
        BottomAxis.Automatic = False
        BottomAxis.AutomaticMaximum = False
        BottomAxis.AutomaticMinimum = False
        BottomAxis.Increment = 10.000000000000000000
        BottomAxis.Maximum = 100.000000000000000000
        BottomAxis.Minimum = -1.000000000000000000
        BottomAxis.Title.Caption = 'Iteration'
        LeftAxis.AxisValuesFormat = '#.0 "x10" E+0'
        LeftAxis.ExactDateTime = False
        LeftAxis.Increment = 1.000000000000000000
        LeftAxis.LabelsExponent = True
        LeftAxis.LabelsFormat.Margins.Left = 0
        LeftAxis.LabelsFormat.Margins.Right = 0
        LeftAxis.LabelsFormat.Margins.Bottom = 0
        LeftAxis.LabelsFormat.Margins.Units = maPercentSize
        LeftAxis.LabelsSeparation = 20
        LeftAxis.Logarithmic = True
        LeftAxis.MaximumOffset = 2
        LeftAxis.MaximumRound = True
        LeftAxis.MinimumOffset = 4
        LeftAxis.Title.Caption = #967'2'
        LeftAxis.Title.Font.Height = -13
        LeftAxis.Title.Shadow.Visible = False
        View3D = False
        View3DOptions.PenZoom = 200
        View3DOptions.CheckBoxZoom = 200
        View3DOptions.ZoomText = ztManual
        ZoomWheel = pmwNormal
        Align = alClient
        BevelOuter = bvNone
        Color = 16771538
        TabOrder = 0
        DesignSize = (
          2080
          268)
        DefaultCanvas = 'TGDIPlusCanvas'
        ColorPaletteIndex = 13
        object btnCopyConvergence: TRzButton
          Left = 1940
          Top = 18
          Width = 118
          Height = 50
          Margins.Left = 6
          Margins.Top = 6
          Margins.Right = 6
          Margins.Bottom = 6
          Anchors = [akTop, akRight]
          Caption = 'Copy'
          TabOrder = 0
          OnClick = btnCopyConvergenceClick
        end
        object lsrConvergence: TLineSeries
          SeriesColor = 16744448
          Title = 'srFitProgress'
          Brush.BackColor = clDefault
          LinePen.Color = clRed
          LinePen.Width = 3
          Pointer.InflateMargins = True
          Pointer.Style = psRectangle
          Stairs = True
          XValues.Name = 'X'
          XValues.Order = loAscending
          YValues.Name = 'Y'
          YValues.Order = loNone
        end
      end
    end
  end
end
