object frameProgressView: TframeProgressView
  Left = 0
  Top = 0
  Width = 600
  Height = 400
  TabOrder = 0
  object Splitter1: TSplitter
    Left = 0
    Top = 254
    Width = 600
    Height = 4
    Cursor = crVSplit
    Align = alBottom
    ExplicitTop = 260
  end
  object lblHeader: TRzLabel
    Left = 0
    Top = 0
    Width = 600
    Height = 18
    Align = alTop
    AutoSize = False
    Color = clGray
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -12
    Font.Name = 'Consolas'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Transparent = False
  end
  object pnlChart: TRzPanel
    AlignWithMargins = True
    Left = 3
    Top = 261
    Width = 594
    Height = 136
    Align = alBottom
    BorderOuter = fsNone
    TabOrder = 0
    Color = 15987699
    object chrtProgress: TChart
      AlignWithMargins = True
      Left = 3
      Top = 3
      Width = 588
      Height = 130
      Cursor = crCross
      Legend.Visible = False
      MarginBottom = 1
      MarginLeft = 1
      MarginRight = 1
      MarginTop = 1
      Title.Font.Height = -13
      Title.Font.Style = [fsBold]
      Title.Text.Strings = (
        'FoM')
      Title.Visible = False
      BottomAxis.Title.Caption = 'Iteration'
      LeftAxis.Title.Caption = 'FoM'
      View3D = False
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      DefaultCanvas = 'TGDIPlusCanvas'
      ColorPaletteIndex = 13
    end
  end
  object MemoLog: TRzMemo
    AlignWithMargins = True
    Left = 3
    Top = 21
    Width = 594
    Height = 230
    Align = alClient
    Color = clInfoBk
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 1
    WordWrap = False
  end
end
