unit unit_MCPVersion;

interface

function ServerVersionString: string;   // FileVersion resource of XRC_MCP.exe, 'unversioned' if none
function GitRevision: string;           // GIT_REV from gitrev.inc
function EngineVersionString: string;   // FileVersion of XRayCalc3.exe beside the server exe, or 'not found'

implementation

uses Winapi.Windows, System.SysUtils, System.IOUtils;

{$I gitrev.inc}   // const GIT_REV = 'abc1234';  - regenerated by the dproj pre-build event

function FileVersionOf(const Path: string): string;
var
  Size, Handle: DWORD; Buffer: TBytes; FixedInfo: PVSFixedFileInfo; InfoLen: UINT;
begin
  Result := '';
  if not TFile.Exists(Path) then Exit;
  Size := GetFileVersionInfoSize(PChar(Path), Handle);
  if Size = 0 then Exit;
  SetLength(Buffer, Size);
  if GetFileVersionInfo(PChar(Path), Handle, Size, @Buffer[0]) and
     VerQueryValue(@Buffer[0], '\', Pointer(FixedInfo), InfoLen) then
    Result := Format('%d.%d.%d.%d', [HiWord(FixedInfo.dwFileVersionMS), LoWord(FixedInfo.dwFileVersionMS),
      HiWord(FixedInfo.dwFileVersionLS), LoWord(FixedInfo.dwFileVersionLS)]);
end;

function ServerVersionString: string;
begin
  Result := FileVersionOf(ParamStr(0));
  if Result = '' then Result := 'unversioned';
end;

function GitRevision: string;
begin
  Result := GIT_REV;
end;

function EngineVersionString: string;
begin
  Result := FileVersionOf(TPath.Combine(ExtractFilePath(ParamStr(0)), 'XRayCalc3.exe'));
  if Result = '' then Result := 'not found';
end;

end.
